# Generated by Django 3.1.2 on 2020-11-05 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=3000, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(3, 'Cancel'), (1, 'Reviewed'), (0, 'Pending')], null=True)),
                ('review', models.CharField(blank=True, max_length=3000, null=True)),
                ('is_seen', models.BooleanField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_review_by', to=settings.AUTH_USER_MODEL)),
                ('seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_seen_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint',
                'ordering': ('-created_at',),
            },
        ),
    ]
