# Generated by Django 3.1.2 on 2020-11-10 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0015_auto_20201110_2238'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('number_of_days', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(2, 'Rejected'), (1, 'Approved'), (0, 'Pending')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancel'), (0, 'Pending'), (1, 'Reviewed')], null=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_days', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_days_used', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_days_left', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to=settings.AUTH_USER_MODEL)),
                ('leave_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_period', to='management.leaveperiod')),
                ('leaves', models.ManyToManyField(blank=True, related_name='staff_leaves', to='staff.Leave')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_staff', to='staff.staff'),
        ),
    ]
