# Generated by Django 3.1.2 on 2020-11-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201110_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='purpose',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Reviewed'), (2, 'Cancel')], null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (2, 'Rejected'), (1, 'Approved')], null=True),
        ),
    ]
