# Generated by Django 3.1.2 on 2020-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Suspended', 'Suspended'), ('Dismissed', 'Dismissed'), ('Active', 'Active'), ('On Leave', 'On Leave')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PHM', 'Pharmacist'), ('HR', 'Human Resource'), ('DR', 'Doctor'), ('HM', 'Hospital Manager'), ('NRS', 'Nurse'), ('IT', 'IT'), ('ACC', 'Accountant'), ('CH', 'Cashier')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AD', 'Administrator'), ('NU', 'Normal Staff'), ('SU', 'Support'), ('MU', 'Manager')], max_length=255, null=True),
        ),
    ]
