# Generated by Django 3.1.2 on 2020-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201110_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PHM', 'Pharmacist'), ('HM', 'Hospital Manager'), ('HR', 'Human Resource'), ('IT', 'IT'), ('NRS', 'Nurse'), ('ACC', 'Accountant'), ('DR', 'Doctor'), ('CH', 'Cashier')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Dismissed', 'Dismissed'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Active', 'Active')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('NU', 'Normal Staff'), ('MU', 'Manager'), ('AD', 'Administrator'), ('SU', 'Support')], max_length=255, null=True),
        ),
    ]
