# Generated by Django 3.1.2 on 2020-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultbill',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='number',
            new_name='number_of_days',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Paid'), (1, 'Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('LB', 'Lab Bills'), ('PB', 'Procedures Bills'), ('CB', 'Card Bills'), ('PhB', 'Pharmacy Bills'), ('WB', 'Ward Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultbill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('LB', 'Lab Bills'), ('PB', 'Procedures Bills'), ('CB', 'Card Bills'), ('PhB', 'Pharmacy Bills'), ('WB', 'Ward Bills')], max_length=100, null=True),
        ),
    ]
