# Generated by Django 3.1.2 on 2020-10-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201027_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedallocate',
            old_name='admitted_at',
            new_name='date_admitted',
        ),
        migrations.RenameField(
            model_name='bedallocate',
            old_name='discharged_at',
            new_name='date_discharged',
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='time_admitted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='time_discharged',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Married', 'Married'), ('Single', 'Single')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('ER', 'Emergency'), ('Ward', 'Ward'), ('OPD', 'OPD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
    ]
