# Generated by Django 3.1.2 on 2020-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20201109_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Hide'), (1, 'Show')], null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD'), ('ER', 'Emergency'), ('Discharged', 'Discharged'), ('Ward', 'Ward')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resource'), ('Management', 'Management'), ('Pharmacy', 'Pharmacy'), ('Ward', 'Ward'), ('Account', 'Account')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (2, 'Rejected'), (1, 'Accepted')], null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
