# Generated by Django 3.1.2 on 2020-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201110_2238'),
        ('management', '0015_auto_20201110_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveperiod',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='leave_period_staffs', to='staff.Staff'),
        ),
    ]
