# Generated by Django 3.1.2 on 2020-11-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20201117_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0016_leaveperiod_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Unassigned', 'Unassigned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Widowed', 'Widowed'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('ER', 'Emergency'), ('Discharged', 'Discharged'), ('Ward', 'Ward'), ('OPD', 'OPD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resource'), ('Pharmacy', 'Pharmacy'), ('Management', 'Management'), ('Ward', 'Ward'), ('Account', 'Account')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], null=True),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Government', 'Government'), ('Donation', 'Donation')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_bill', to='portal.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_patient', to='management.patient')),
            ],
            options={
                'db_table': 'revenue',
                'ordering': ('-created_at',),
            },
        ),
    ]
