# Generated by Django 3.1.2 on 2020-11-18 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20201117_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Show'), (0, 'Hide')], null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Married', 'Married')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('Discharged', 'Discharged'), ('OPD', 'OPD'), ('ER', 'Emergency'), ('Ward', 'Ward')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('Account', 'Account'), ('Ward', 'Ward'), ('Pharmacy', 'Pharmacy'), ('HR', 'Human Resource'), ('Management', 'Management')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Rejected'), (1, 'Accepted'), (0, 'Pending')], null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='stream',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Donation', 'Donation'), ('Government', 'Government')], max_length=100, null=True),
        ),
    ]
