# Generated by Django 3.1.2 on 2020-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_auto_20201112_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_paid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Confirmed')], null=True),
        ),
    ]
